### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by Omtrw** [DanielLChapman/SW-Fusion-Mart#1]
Not an issue but just wanna ask what that was use for?

**Comment by DanielLChapman** [comment]
What what was used for? If you mean the whole application, it was an idea I had after a surgery that on pain killers sounded hilarious to me. Now its just a fun idea to use with trying out the create-react-app. Its for a mobile game (SW) to determine what you need in order to fuse X amount of Y units in the game. Basically just a semi-complicated excel sheet being turned into a react app. If its something else, let me know what part of the code and I can explain my reasoning.

**Comment by Omtrw** [comment]
Exactly what I was asking, thanks
